import type { AddressValue, MossRuntime, TransactionNode } from "@themoss/core";

export type MarketCandidate = Readonly<{
  market: AddressValue;
  expectedUnderlying: AddressValue;
  metadata: PendleApiMarketMetadata;
}>;

export type MarketVerificationCandidate = Readonly<{
  market: string;
  expectedUnderlying: string;
}>;

export type PendleApiMarketMetadata = Readonly<{
  name: string;
  protocol: string;
  expiry: string;
  // Decimal fraction as returned by the Pendle API, not a percentage: 0.05 means 5% APY.
  aggregatedApy?: number;
  provenance: Readonly<{
    kind: "inferred";
    provider: "Pendle official API";
    source: string;
    fetchedAt: string;
  }>;
}>;

export type VerifiedMarket = Readonly<{
  market: AddressValue;
  factory: AddressValue;
  sy: AddressValue;
  pt: AddressValue;
  yt: AddressValue;
  underlying: AddressValue;
  decimals: Readonly<{
    underlying: number;
    pt: number;
  }>;
  expiry: bigint;
  tokenSupport: Readonly<{
    tokensIn: readonly AddressValue[];
    tokensOut: readonly AddressValue[];
    underlyingIn: boolean;
    underlyingOut: boolean;
  }>;
}>;

export type DiscoveredPendleMarket = Readonly<{
  market: VerifiedMarket;
  metadata: PendleApiMarketMetadata;
}>;

export type MarketDiscoveryRejection = Readonly<{
  stage: "candidate-schema" | "duplicate-candidate" | MarketVerificationStage;
  candidate?: AddressValue;
  reason: string;
}>;

export type PendleMarketDiscoveryResult = Readonly<{
  status: "available" | "unavailable";
  candidateCount: number;
  verified: readonly DiscoveredPendleMarket[];
  rejections: readonly MarketDiscoveryRejection[];
}>;

export type PendleMarketVerifier = (
  runtime: MossRuntime,
  candidate: MarketCandidate,
) => Promise<VerifiedMarket>;

export type PendleSwapDirection = "buy-pt" | "sell-pt";

/**
 * Pendle Router binary-search bounds generated by RouterStatic for a token-in swap;
 * carried verbatim into the eventual Router transaction, never recomputed off-chain.
 */
export type PendleApproxParams = Readonly<{
  guessMin: bigint;
  guessMax: bigint;
  guessOffchain: bigint;
  maxIteration: bigint;
  eps: bigint;
}>;

export type PendleQuoteParams = Readonly<{
  tokenIn: string;
  tokenOut: string;
  amountIn: bigint;
  slippageBps: number;
}>;

type PendleQuoteBase = Readonly<{
  direction: PendleSwapDirection;
  market: AddressValue;
  tokenIn: AddressValue;
  tokenOut: AddressValue;
  amountIn: bigint;
  expectedOut: bigint;
  minOut: bigint;
  slippageBps: number;
  decimals: Readonly<{ in: number; out: number }>;
}>;

export type PendleBuyPtQuote = PendleQuoteBase &
  Readonly<{ direction: "buy-pt"; approxParams: PendleApproxParams }>;

export type PendleSellPtQuote = PendleQuoteBase & Readonly<{ direction: "sell-pt" }>;

/**
 * A read-only RouterStatic quote. `approxParams` is present exactly when `direction` is "buy-pt".
 */
export type PendleQuote = PendleBuyPtQuote | PendleSellPtQuote;

export type PendleQuoteStage = "params" | "direction" | "router-static-read" | "min-out";

/**
 * The nested ERC20 allowance a Pendle swap needs before its Router call; `amount` is raw minimal units.
 */
export type PendleApprovalRequirement = Readonly<{
  token: AddressValue;
  spender: AddressValue;
  amount: bigint;
}>;

/**
 * One direct Pendle Router swap transaction plus the ERC20 approval it depends on.
 */
export type PendleSwapPlan = Readonly<{
  direction: PendleSwapDirection;
  approval: PendleApprovalRequirement;
  transaction: TransactionNode;
}>;

/**
 * The settled result of a Pendle PT swap, derived entirely from the Router `SwapPtAndToken` event.
 * `amountIn`/`amountOut` are raw minimal units as strings; the PT side is identified by `direction`.
 */
export type PendleSwapOutcome = Readonly<{
  operation: "swap";
  protocol: "pendle";
  direction: PendleSwapDirection;
  market: AddressValue;
  token: AddressValue;
  caller: AddressValue;
  receiver: AddressValue;
  amountIn: string;
  amountOut: string;
}>;

/**
 * A read-only swap quote in display units for the public `quote` Query.
 */
export type PendleQuoteView = Readonly<{
  direction: PendleSwapDirection;
  market: AddressValue;
  tokenIn: AddressValue;
  tokenOut: AddressValue;
  amountIn: string;
  estimatedOut: string;
  minOut: string;
  expiryUtc: string;
}>;

/**
 * One verified market for the public `markets` Query. `aggregatedApy` is Pendle-API inferred data,
 * carried with its provenance and never presented as an on-chain guarantee. It is a decimal fraction,
 * not a percentage: 0.05 means 5% APY. `null` when the API reported no value.
 */
export type PendleMarketView = Readonly<{
  market: AddressValue;
  underlying: AddressValue;
  pt: AddressValue;
  sy: AddressValue;
  expiryUtc: string;
  decimals: Readonly<{ underlying: number; pt: number }>;
  name: string;
  protocol: string;
  aggregatedApy: number | null;
  apyProvenance: PendleApiMarketMetadata["provenance"];
}>;

/**
 * Isolates untrusted RouterStatic reads so the quoter can validate every returned value before use.
 */
export interface PendleQuoteReader {
  quoteExactTokenForPt(
    market: AddressValue,
    tokenIn: AddressValue,
    amountTokenIn: bigint,
    slippage: bigint,
  ): Promise<unknown>;
  quoteExactPtForToken(
    market: AddressValue,
    exactPtIn: bigint,
    tokenOut: AddressValue,
  ): Promise<unknown>;
}

export type PendleDiscoveryFetch = (input: URL, init?: RequestInit) => Promise<Response>;

export type MarketVerificationStage =
  | "candidate"
  | "chain"
  | "market-bytecode"
  | "factory-registration"
  | "factory-getter"
  | "read-tokens"
  | "underlying-identity"
  | "dynamic-bytecode"
  | "expiry"
  | "token-support-in"
  | "token-support-out"
  | "decimals";

/**
 * Isolates untrusted chain-read results so the verifier can validate every ABI value before use.
 */
export interface MarketVerificationReader {
  chainId(): Promise<unknown>;
  codeAt(address: AddressValue): Promise<unknown>;
  isValidMarket(market: AddressValue): Promise<unknown>;
  marketFactory(market: AddressValue): Promise<unknown>;
  marketTokens(market: AddressValue): Promise<unknown>;
  marketExpiry(market: AddressValue): Promise<unknown>;
  yieldToken(sy: AddressValue): Promise<unknown>;
  tokensIn(sy: AddressValue): Promise<unknown>;
  tokensOut(sy: AddressValue): Promise<unknown>;
  decimals(token: AddressValue): Promise<unknown>;
  latestBlockTimestamp(): Promise<unknown>;
}
